### ISSUE TITLE
Shooter thingy

### ISSUE THREAD

**Issue by Clone5030** [nhatbh/fireworks#1]
The shooter thingy will disappear after going too far left or right of the window and it won't appear until reloading.

**Comment by nhatbh** [comment]
The reason why it dissapear is due to memory optimization of the rendering engine which will delete any entity that goes too far over the boundary. It should be rather easy to implement a fix as I can just prevent the shooter from ever leaving the screen in the first place. So if I have time, mayyyybe I'll commit a patch just for fun and shit but currently I will take this as a feature and not a bug.

Best regards

Trumptheduck

P/S: Haven't visit this repository for month's lol, so sorry for the late issue response
